apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-http
  namespace: default
  annotations:
    # Use ingressClassName instead of deprecated annotation
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/backend-protocol: "http"
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-app-service
            port:
              number: 80

